spring:
  application:
     name: product-composite-service

app:
  product-service:
    host: localhost
    port: 8000
  review-service:
    host: localhost
    port: 8100
  recommendation-service:
    host: localhost
    port: 8200
