server:
  port: 8002
spring:
  application:
    name: recommendation-service

---
spring:
  application:
    name: recommendation-service
  config:
    activate:
      on-profile: docker
server:
  port: 8080