
server:
    port: 8002

aws:
  dynamodb:
     region: us-east-1
     endpoint: http://localhost:8000/

spring:
  application:
    name: recommendation-service
  data:
    mongodb:
      host: localhost
      port: 27017
logging:
  level:
    com:
      amazonaws:
        services:
          dynamodbv2: DEBUG
---
spring:
  application:
    name: recommendation-service
  config:
    activate:
      on-profile: docker
  data:
    mongodb:
      host: mongodb
server:
  port: 8080