
server:
  port: 8080
aws:
  dynamodb:
    region: us-east-1
    endpoint: http://dynamoDb:8000/
spring:
  application:
    name: recommendation-service
logging:
  level:
    com:
      amazonaws:
        services:
          dynamodbv2: DEBUG