server:
  port: 8000
spring:
   application:
     name: product-service
   data:
     mongodb:
       host: localhost
       port: 27017

---
spring:
  application:
    name: product-service
  config:
    activate:
      on-profile: docker
server:
  port: 8080