server:
  port: 8009

spring:
  data:
   mongodb:
      host: 127.0.0.1
      port: 27017
      database: product-db
  cloud:
    stream:
      bindings:
        myConsumer-in-0:
          destination: product
          group: my-consumer-group
      kafka:
        binder:
          brokers: localhost:9092
          consumer-properties:
            enable.auto.commit: false

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
---
spring:
  application:
    name: product-service
  config:
    activate:
      on-profile: docker
  data:
    mongodb:
      host: mongodb
server:
  port: 8080