server:
  port: 8001
spring:
  application:
        name: review-service
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/postgres
    username: admin
    password: admin
  sql:
    init:
      mode: always



---
spring:
  application:
    name: review-service
  config:
    activate:
      on-profile: docker
server:
  port: 8080